const menu = [
  {
    id: 1,
    title: 'AVOCADO POACHED EGGS',
    titleAr: 'أفوكادو بوتشد إيقز',
    categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 3.250,
    img: '/images/Avocado-Poached-Eggs.jpg',
    desc: `2 eggs, avocado /guacamole, mix capsicum, sourdough bread,butter`,
    descAr: `اثنان (2) بيض نصف سلق ، لحم بقري مفروم ، أعشاب متنوعة ، بذور السمسم ، صلصة هولانديز`,
  },                                    
  {
    id: 2,
    title: 'BERRIES FRENCH TOAST',
    titleAr: 'توست فرنسي بالتوت',
    categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 3.500,
    img: '/images/Berries-French-Toast.jpg',
    desc: 'FRENCH TOAST, MIX BERRIES, MAPLE ',
    descAr: `توست فرنسي ، توت مشكل ، مابل سيريب`,
  },
 {
    id: 3,
    title: 'PINK PANCAKES (OPTION W/ MAPLE OR CHOCOLATE SAUCE)',
    titleAr: 'بينك بان كيك (إختيار مع مابل سيريب أو الشوكولاته)',
    categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 3.00,
    img: '/images/Pink-Pancake-chocolate.jpg',
    desc: `3 PCS PANCAKES, MIX BERRIES, ICING SUGAR, MAPLE SYRUP, BUTTER`,
    descAr: ` ثلاث (3) قطع بان كيك ، توت مشكل ، بودرة سكر ، مابل سيريب ، زبدة `,
 },
  {
    id: 4,
    title: 'SHAKSHOKA',
    titleAr: 'شكشوكة',
    categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 3.500,
    img: '/images/Shakshoka-new.jpg',
    desc: `GRILLED EGGS, MUSHROOM, TOMATO, ONION, FETA CHEESE, `,
    descAr: `بيض مشوي ، مشروم ، طماطم ، بصل ، جبنة فيتا`,
  },
  {
    id: 5,
    title: 'CLUB SANDWICH AND FRIES',
    titleAr: 'كلوب ساندويتش مع بطاط',
       categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 4.500,
    img: '/images/sandwich.jpg',
    desc: `WHITE BREAD, MIX RANCH MAYO, TURKEY, TURKEY BACON, LETTUCE,TOMATO, EGG, SWISS CHEESE`,
    descAr: `خبز ابيض ، ميكس رانش مايو ، تركي الديك الرومي ،تركي اللحم المقدد ، خس ، طماطم ، بيضة ، جبنة سويسرية`,
  },
  {
    id: 6,
    title: 'CLASSIC EGGS BENEDICT',
    titleAr: 'بيض بينديكت الكلاسيكيه',
    categoryEn: 'breakfast',
    category: 'Breakfast/الفطور',
    price: 3.500,
    img: '/images/Classic-Egg-Benedict-new.jpg',
    desc: `2 POUCHED EGG, MINCED BEEF, ASSORTED HERBS, SESAME SEED HOLLANDISE SAUCE `,
    descAr: ` ثلاث (3) بيض نصف سلق ، لحم بقري مفروم ، أعشاب متنوعة ، بذور السمسم ، صلصة هولانديز `,
  },
  {
    id: 7,
    title: 'CHICKEN QUESADILLA W/ SWEET POTATO',
    titleAr: 'كاسادييا بالدجاج مع بطاطا حلوه',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.500,
    img: '/images/Chicken-Quesadilla-with-Sweet-Potatoes.jpg',
    desc: `TORTILLA BREAD, MIX RANCH CHIVES, DICED CHICKEN, BLACK OLIVES,
            MIX CAPSICUMS, CORN, MOZZARELLA CHEESE, POTATOES, ARUGULA,
            CARROTS, SIGNATURE SAUCE, SWEET POTATO FRIES`,
    descAr: ` خبز تورتيلا ، ميكس رانش ثوم ، مكعبات دجاج ، زيتون أسود ، فليفلة
    مشكلة ، ذرة ، جبنة موزاريلا ، بطاطس ، جرجير ، جزر ، صلصة خاصة ،
    بطاطا حلوة`,
  },
  {
    id: 8,
    title: 'VOLCANO BITES',
    titleAr: 'ڤولكينو بايتس',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.750,
    img: '/images/Volcano-Bites.jpg',
    desc: `CHICKEN BREAST WITH SPICY SAUCE, CARROTS, RANCH SAUCE`,
    descAr: `دجاج مع صلصة حارة، جزر ، صلصة رانش`,
  },
  {
    id: 9,
    title: 'STREET STYLE FRIES',
    titleAr: 'ستريت ستايل فرايز',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.500,
    img: '/images/Street-style-fries.jpg',
    desc: `FRESH CUT FRIES, SPECIAL SAUCE, GRILLED ONION, FRIED ONION,
          PARMESAN CHEESE, CHEESE SAUCE, GARNISH SPRING ONION`,
    descAr: `بطاطا مقلية طازجة، صلصة خاصة، بصل مشوي ، بصل مقلي، جبنة
    بارميزان ، صوص جبنة، بصل أخضر مقبلات`,
  },
  {
    id: 10,
    title: 'MOZARELLA BALLS',
    titleAr: 'كرات الموزاريل',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.250,
    img: '/images/Mzzarella-Balls.jpg',
    desc: `FRESH MUSHROM, MOZZARELLA CHEESE, SRIRACHA SAUCE`,
    descAr: `فطر فريش ، جبنة موزاريلا ، صلصة سريراتشا`,
  },
  {
    id: 11,
    title: 'DYNAMITE PINK SHRIMP',
    titleAr: 'دايناميت بينك شريمب',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 4.250,
    img: '/images/Pink-dynamite-shrimp.jpg',
    desc: `8 PCS SHIRMP, PINK SAUCE, SPRING ONION, LOLOBIANDO LETTUCE`,
    descAr: ` ثمان (8) قطع ربيان ، صلصة وردية، بصل أخضر ، خس لوبيوندو `,
  },
  {
    id: 12,
    title: 'LOS ANGELES FRIES',
    titleAr: 'بطاط لوس انجلوس',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.500,
    img: '/images/Los-Angeles-Fries.jpg',
    desc: `FRESH CUT FRIES, SAUCE, CARAMELIZED ONION, CHEESE SAUCE`,
    descAr: `بطاطا مقلية طازجة ، صوص ، بصل مكرمل ، صوص جبنة`,
  },
  {
    id: 13,
    title: 'BUFFALO CHICKEN',
    titleAr: 'بافلو دجاج',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.750,
    img: '/images/Buffalo-Chicken.jpg',
    desc: `6 PCS CHICKEN, ONION, WORCESTERSHIRE SAUCE, BROWNE
          SUGAR, WHITE PEPPER, RED HOT SAUCE, SRIRACHA, HONEY,
          CILANTRO GREEN PASTE`,
          descAr: ` ستة (6) قطع دجاج ، بصل ، صلصة رسيستيرشاير ، سكر بني ، فلفل أبيض 
          صوص أحمر حار ، سريراتشا ، عسل ، عجينة الكزبرة الخضراء `,
  },
  {
    id: 14,
    title: 'BUFFALO SHRIMP',
    titleAr: 'بافلو شريمب',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 3.750,
    img: '/images/Buffalo-Shrimp.jpg',
    desc: `6 PCS SHRIMP, ONION, WORCESTERSHIRE SAUCE, BROWNE
          SUGAR, WHITE PEPPER, RED HOT SAUCE, SRIRACHA, HONEY,
          CILANTRO GREEN PASTE`,
          descAr: ` ستة (6) قطع ربيان  بصل ، صلصة رسيستيرشاير ، سكر بني ، فلفل أبيض
          صوص أحمر حار ، سريراتشا ، عسل ، عجينة الكزبرة الخضراء `,
  },
  
  {
    id: 15,
    title: 'BUFFALO MIX (CHICKEN + SHRIMP)',
    titleAr: 'ميكس البافلو ( دجاج + شريمب )',
    categoryEn: 'appetizers',
    category: 'Appetizers / المقبلات',
    price: 4.250,
    img: '/images/Buffalo-Mix.jpg',
    desc: `4 PCS CHICKEN, 4 PCS SHRIMP, ONION, WORCESTERSHIRE
          SAUCE, BROWNE SUGAR, WHITE PEPPER, RED HOT SAUCE,
          SRIRACHA, HONEY, CILANTRO GREEN PASTE`,
          descAr: ` أربع (4) قطع دجاج ، 4 قطع ربيان ، بصل ، صلصة رسيستيرشاير ، سكر بني
          فلفل أبيض ، صوص أحمر حار ، سريراتشا ، عسل ، عجينة الكزبرة الخضراء`,
  },

  {
    id: 16,
    title: 'STRAWBERRY FETA',
    titleAr: 'سلطة الفيتا بالفراولة',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Strawberry-Feta.jpg',
    desc: `ROCCA, FRESH STRAWBERRIES, FETA CHEESE, ALMONDS, SLICE PINE
           NUTS, BALSAMIC VINAIGRETTE`,
    descAr: `جرجير ، فراولة طازجة ، جبنة فيتا ، لوز ، شرائح صنوبر ، خل بلسميك`,
  },
  {
    id: 17,
    title: 'CEASER (OPTION W/ CHICKEN OR SHRIMP)',
    titleAr: 'سيزر (إختيار مع / دجاج او ربيان)',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Caesar-Salad.jpg',
    desc: `LETTUCE, BLACK OLIVE, CROUTONS, RANCH, PARMESAN CHEESE`,
    descAr: `خس ، زيتون أسود ، خبز محمص ، رانش ، جبنة بارميزان`,
  },
  {
    id: 18,
    title: 'POWERHOUSE QUINOA',
    titleAr: 'باور هاوس كينو',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Powerhouse-Quinoa-Salad.jpg',
    desc: `ROCCA, QUINOA, CORN, EDAMAME, AVOCADO, CRANBERRIES,
          PARSLEY, ALMONDS, FETA CHEESE`,
    descAr: `جرجير ، كينوا ، ذرة ، ادامامي ، افوكادو ، توت بري ، بقدونس ، لوز ،
    جبنة فيتا`,
  },
  {
    id: 19,
    title: 'BEETROOT SALAD',
    titleAr: 'سلطة الشمندر',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Beetroot-Salad.jpg',
    desc: `ROCCA, FRESH BEETROOT, SPINACH, FETA CHEESE, POMEGRANATE,
    PINE NUTS, BALSAMIC VINAIGRETTE`,
    descAr: `جرجير ، شمندر طازج ، سبانخ ، جبنة فيتا ، رمان ، صنوبر ، خل بلسميك`,
  },
  {
    id: 20,
    title: 'DORITOS BACON',
    titleAr: 'دوريتوس بيكن',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Dorito-Salad.jpg',
    desc: `CABBAGE, SWEET CORN, ROMAINE LETTUCE, TOMATO, ONION
    CARROTS, CHIVES, DORITOS, RANCH, CORIANDER`,
    descAr: `ملفوف ، ذرة حلوة ، خس ، طماطم ، بصل، جزر ، ثوم ، دوريتوس ،
    رانش ، كزبرة`,
  },
  {
    id: 21,
    title: 'SPICY CRAB',
    titleAr: 'سبايسي كراب',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Spicy-Crab-Salad.jpg',
    desc: `CARROTS, CUCUMBER, MANGO, CABBAGE, SWEET SPICY MAYO
    SAUCE, SHREDDED ICEBERG LETTUCE, CRAB SHREDDED, AVOCADO`,
    descAr: `جزر ، خيار ، مانجو ، ملفوف ، صوص مايو حار حلو ، خس ايسبيرج
    مبشور ، كابوريا مبشور ، افوكادو`,
  },
  {
    id: 22,
    title: 'PECAN STRAWBERRY SALAD ',
    titleAr: 'سلطة الفراولة والبيكان ',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.750,
    img: '/images/salads/Peacan-Strawberry-salad.jpg',
    desc: `ARUGULA, BABY SPINACH, LOLO ROSSO, FRESH STRAWBERRY,
          JACKFRUIT, ROASTED PECAN, FETA CHEESE, PARMESAN CHIPS, FRESH
          ORANGE JUICE, FRESH LEMON JUICE, DIJON MUSTARD, HONEY,
          BALSAMIC VINAIGRETTE, SALT & WHITE PEPPER`,
    descAr: `جرجير ، سبانخ صغير ، لولو روسو ، فراولة طازجة ، جاك فروت ، بيكان
    محمص ، جبنة فيتا ، رقائق بارميزان ، عصير برتقال طازج ، عصير ليمون
    طازج ، خردل ديجون ، عسل ، خل بلسميك ، ملح وفلفل أبيض`,
  },
  {
    id: 23,
    title: 'CLASSIC CEASAR SALAD',
    titleAr: 'سلطة السيزر الكلاسيكية',
    categoryEn: 'salads',
    category: 'Salads / السلطات',
    price: 3.250,
    img: '/images/salads/Caesar-Salad-classic.jpg',
    desc: `LETTUCE ROMAINE, CAESAR DRESSING, GARLIC CROUTON, PARMESAN
    CHEESE, GRILLED CHICKEN, MAYONNAISE, YELLOW MUSTARD, WHITE
    VINEGAR, GARLIC, CAPERS ANCHOVIES`,
    descAr: `خس رومين ، صلصة سيزر ، خبز محمص بالثوم ، جبنة بارميزان ، دجاج
    مشوي ، مايونيز ، خردل أصفر ، خل أبيض ، ثوم ، أنشوجة كبر`,
  },
   {
    id: 23,
    title: 'BRISKET',
    titleAr: 'بريسكت',
    categoryEn: 'burgers',
    category: 'Burgers / برجر',
    price: 4.500,
    img: '/images/burgers/Brisket.jpg',
    desc: `BEEF BRISKET, CHOPPED LETTUCE, WHITE ONION`,
    descAr: `بريسكت لحم بقري ، خس مقطع ، بصل أبيض ، ملح وفلفل ، مسحوق
    فلفل حار`,
   },
   {
    id: 24,
    title: 'CLASSIC LOS ANGELES',
    titleAr: 'كلاسيك لوس انجلوس',
     categoryEn: 'burgers',
    category: 'Burgers / برجر',
    price: 3.750,
    img: '/images/burgers/Classic-Los-Angeles.jpg',
    desc: `PATTY, CARAMELIZED ONION, MUSTARD, CHEESE, PICKLES, LETTUCE, 
    TOMATO, SPECIAL SAUCE`,
    descAr: `شريحة لحم ، بصل مكرمل ، خردل ، جبنة ، مخلل ، خس ، طماطم ،
    صوص خاصة`,
   },
   {
    id: 25,
    title: 'GRILLED CHICKEN BURGER',
    titleAr: 'برغر الدجاج المشوي',
     categoryEn: 'burgers',
    category: 'Burgers / برجر',
    price: 4.500,
    img: '/images/burgers/Grill-Chicken-Burger.jpg',
    desc: `CHICKEN, MUSTARD, CHEESE, PICKLES, ONIONS, LETTUCE, TOMATOES, 
    SPECIAL SAUCE`,
    descAr: `دجاج ، بصل ، خردل ، جبنة ، مخلل ، خس ، طماطم ، صوص خاصة`,
   },
   {
    id: 26,
    title: 'CLASSIC CRUNCHY CHICKEN',
    titleAr: 'كلاسيك دجاج كرنشي',
     categoryEn: 'burgers',
    category: 'Burgers / برجر',
    price: 3.500,
    img: '/images/burgers/Classic-Crunchy-Chicken.jpg',
    desc: `CRISPY CHICKEN BREAST, RED CABBAGE, CARROTS, LETTUCE, 
    PICKLES, CHEESE, YUMMY SAUCE`,
    descAr: `صدر دجاج مقرمش ، ملفوف أحمر ، جزر ، خس ، مخلل ، جبن ، صلصة لذيذة`,
   },
   {
    id: 27,
    title: 'SLIDERS (CHICKEN OR BEEF)',
    titleAr: 'سلايدر (دجاج او لحم بقري)',
     categoryEn: 'burgers',
    category: 'Burgers / برجر',
    price: 3.750,
    img: '/images/burgers/Sliders.jpeg',
    desc: `2 PCS CHICKEN OR BEEF PATTIES, CHEESE, LETTUCE, ONIONS, 
    PICKLES, REGULAR FRIES, KETCHUP`,
    descAr: `قطعتين دجاج أو لحم بقري ، جبن ، خس ، بصل ، مخلل ، بطاطا حجم
    عادي ، كاتشب`,
   },
   {
    id: 28,
    title: 'LITTLE ITALY PIZZA',
    titleAr: 'بيتزا ليتل إيطالي',
    categoryEn: 'pizza',
    category: 'Pizza / بيتزا',
    price: 3.750,
    img: '/images/pizza/pizza1.jpg',
    desc: `PIZZA DOUGH, TOMATO SAUCE, PEPPERONI, OLIVE OIL, ROCCA, 
    OREGANO, MOZZARELLA CHEESE`,
    descAr: `عجينة بيتزا ، صلصة طماطم ، بيبروني ، زيت زيتون ، جرجير ، اوريجانو ،
    جبنة موتزاريل`,
   },
   {
    id: 29,
    title: 'PINK’S SIGNATURE MARGHERITA',
    titleAr: 'بينك سيجنتشر مارغريتا',
    categoryEn: 'pizza',
    category: 'Pizza / بيتزا',
    price: 3.500,
    img: '/images/pizza/pizza2.jpg',
    desc: `PIZZA DOUGH, PINK SAUCE, OLIVE OIL, OREGANO, MOZZARELLA 
    CHEESE`,
    descAr: 'عجينة بيتزا ، صلصة وردية ، زيت زيتون ، زعتر ، جبنة موتزاريل',
   },
   {
    id: 30,
    title: 'RED PASTA W/ PARMESAN CHEESE',
    titleAr: 'باستا صوص أحمر مع جبنة البرميزان',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.500,
    img: '/images/maincourse/Red-Pasta-With-Parmesan-Cheese.jpg',
    desc: `PAPPARDELLE, CHICKEN CUBES, GRILLED CHERRY TOMATO, PARSLEY, 
    BASIL, ROMARA RED SAUCE, BASIL AND , PARSLEY, PARMESAN CHEESE`,
    descAr:`بابارديل ، مكعبات دجاج ، طماطم كرزية مشوية ، بقدونس ، ريحان،
    صلصة رومارا حمراء ، ريحان ، بقدونس ، جبنة بارميزان`
   },
   {
    id: 31,
    title: 'CLASSY PINK PENNE',
    titleAr: 'كلاسي بينك بيني',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.500,
    img: '/images/maincourse/Classy-Pink-Penne-Pasta.jpg',
    desc: `PENNE PASTA, BETROOT, OLIVE OIL, OREGANO, SHALLOTS, MIX 
    PARMESAN & MOZZARELLA CHEESE`,
    descAr: `بيني باستا ، شمندر ، زيت زيتون ، اوريجانو ، كراث ، خليط جبنة
    بارميزان و موزاريل`,
   },
   {
    id: 32,
    title: 'CREAMY SHRIMP (OPTION W/ CHICKEN)', 
    titleAr: '(ربيان كريمي (إختيار مع/ دجاج',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 4.250,
    img: '/images/maincourse/creamypasta.jpg',
    desc: `SHRIMP, OREGANO, MIX PARMESAN & MOZZARELLA CHEESE`,
    descAr: `روبيان ، كريمة طبخ، اوريجانو، ميكس بارميزان و جبنة موتزاريل`,
   },
   {
    id: 33,
    title: 'PINK STEAK BURGER',
    titleAr: 'بينك ستيك برجر',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.500,
    img: '/images/maincourse/Pink-Steak-burger.jpg',
    desc: `2 BURGER PATTIES, MASHED POTATOES, MUSHROOM SAUCE`,
    descAr: `قطعتين برجر ، بطاطس مهروسة ، صوص مشروم`,
   },
   {
    id: 34,
    title: 'SHRIMP TACOS W/ GUACAMOLE',
    titleAr: 'تاكوس ربيان مع الجواكامولي',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.750,
    img: '/images/maincourse/Shrimp-Tacos-With-Guacamole.jpg',
    desc: `FAJITA SHRIMP, WHITE ONION, MIX CAPSICUM, GUACAMOLE, GARLIC 
    MAYO, MIX CHEESE`,
    descAr: `روبيان فاهيتا ، بصل أبيض ، مزيج الفلفل ، جواكامولي ، مايونيز
    بالثوم ، مزيج الجبن
    `,
   },
   {
    id: 35,
    title: 'TENDERLOIN STEAK SIGNATURE BY PINK',
    titleAr: 'تندرلوين ستيك سيجنتشر من بينك',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 7.750,
    //img: '/images/maincourse/pizza2.jpg',
    desc: `BEEF TENDERLOIN, MIX MUSH POTATO, GRILLED CORN, SALSA VERDE`,
    descAr: `لحم بقري تندرلوين ، مزيج بطاطا مهروسة ، ذرة مشوية ، صلصة
    خضراء`,
   },
   {
    id: 36,
    title: 'HERB CRUSTED TENDERLOIN',
    titleAr: 'تندرليون بالاعشاب',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 4.750,
    img: '/images/maincourse/Herb-Crusted-Tenderloin.jpg',
    desc: `TENDERLOIN, CHICKPEAS, RED CAPSICUM, SWEET POTATO, HERBS, 
    CREAMY MUSTARD SAUCE`,
    descAr: `تندرليون ، حمص ، فلفل أحمر ، بطاطا حلوة ، أعشاب ، صلصة
    كريمة الخردل`,
   },
   {
    id: 37,
    title: 'STEAK & BROCCOLI',
    titleAr: 'ستيك وبروكلي',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.750,
    img: '/images/maincourse/Steak-And-Broccoli.jpg',
    desc: `TENDERLOIN, BROCCOLI, CHEESE SAUCE, MIX CHEESE, PINE NUTS, 
    MUSHROOM SAUC`,
    descAr: `تندرلوين ، بروكلي ، صوص جبن ، ميكس جبن ، صنوبر ، صوص مشروم`,
   },
   {
    id: 38,
    title: 'GRILLED CHICKEN W/ASPARAGUS CHERRY TOMATOES',
    titleAr: 'دجاج مشوي مع طماطم كرزية وهليون',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 5.500,
    //img: '/images/maincourse/pizza2.jpg',
    desc: `GRILLED CHICKEN, ROMARA SAUCE, GRILLED LEAK, COCONUT SOUR 
    DRESSING, CHERRY TOMATOES, ASPARAGUS`,
    descAr: `دجاج مشوي ، صلصة رومارا ، مشوي مسرب ، صلصة جوز الهند
    الحامضة ، طماطم كرزية ، هليون`,
   },
   {
    id: 39,
    title: 'HERBAL CHICKEN & RICE',
    titleAr: 'أرز ودجاج بالأعشاب',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.750,
    //img: '/images/maincourse/pizza2.jpg',
    desc: `CHICKEN BREAST, ASSORTED CAPSICUM, RICE, SPRING ONION, WHITE 
    & TASTY SAUCE`,
    descAr: `صدر دجاج ، فلفل مشكل ، أرز ، بصل أخضر ، صلصة بيضاء و لذيذة`,
   },
   {
    id: 40,
    title: 'CHICKEN & SAUTÉ VEGETABLE',
    titleAr: 'دجاج وخضار سوتيه',
    categoryEn: 'maincourse',
    category: 'Main Course / أطباق رئيسية',
    price: 3.750,
    img: '/images/maincourse/Chicken-And-Saute-Vegetables.jpg',
    desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    BEANS`,
    descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 41,
    title: 'BERRIES FRENCH TOAST',
    titleAr: 'توست فرنسي بالتوت',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.500,
    img: '/images/desserts/Berries-French-Toast.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 42,
    title: 'SAFRON CAKE',
    titleAr: 'كيك الزعفران',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 43,
    title: 'PINK MOLTEN',
    titleAr: 'مولتن بينك',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 44,
    title: 'SIGNATURE PINK CHEESECAKE',
    titleAr: 'تشيز كيك بينك سيجنتشر',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 45,
    title: 'RED VELVET CAKE',
    titleAr: 'ريد فيلفيت كيك',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.250,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 46,
    title: 'HONEY CAKE',
    titleAr: 'كيكة بالعسل',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 47,
    title: 'CHOCOLATE CAKE',
    titleAr: 'كيكة الشوكولاتة',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.250,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 48,
    title: 'LOTUS / KINDER / NUTELLA CRÊPE',
    titleAr: 'كريب لوتس / كيندر / نوتيل',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 49,
    title: 'KINDER RUSH',
    titleAr: 'كندر رش',
    categoryEn: 'desserts',
    category: 'Desserts / حلويات',
    price: 3.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 50,
    title: 'ROSE COFFEE',
    titleAr: 'روز كوفي',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 51,
    title: 'ARABIC COFFEE DALLAH (4 PERSONS)',
    titleAr: 'قهوة عربية (دلة)',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 3.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 52,
    title: 'CARAMEL LATTE',
    titleAr: 'كراميل لاتيه',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 53,
    title: 'LATTE CLASSIC',
    titleAr: 'كلاسيك لاتيه',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.250,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 54,
    title: 'VANILLA / GOLDEN LATTE',
    titleAr: 'فانيليا / جولدن لاتيه',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 55,
    title: 'SPANISH LATTE',
    titleAr: 'لاتية أسباني',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 56,
    title: 'CAPPUCINO',
    titleAr: 'كابتشينو',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 57,
    title: 'FLAT WHITE',
    titleAr: 'فلات وايت',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 58,
    title: 'BLACK / GREEN TEA',
    titleAr: 'شاي اسود / اخضر',
    categoryEn: 'hotdrinks',
    category: 'HOT DRINKS / مشروبات ساخنه',
    price: 2.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },
   {
    id: 59,
    title: 'BLUE LAGOON',
    titleAr: 'بلو لاجون',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 60,
    title: 'BERRIES MOCKTAIL',
    titleAr: 'بيريز موكتيل',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.750,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 61,
    title: 'PINK SIGNATURE LEMONADE',
    titleAr: 'ليمون بينك سجنتشر',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 62,
    title: 'PINK’S SIGNATURE ICED LATTE',
    titleAr: 'لاتية مثلج بينك سجنتشر',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 63,
    title: 'CARAMEL LATTE',
    titleAr: 'كراميل لاتيه',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 64,
    title: 'ICED SPANISH LATTE',
    titleAr: 'لاتيه أسباني مثلج',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 65,
    title: 'ROSE LATTE',
    titleAr: 'روز لاتيه',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 66,
    title: 'LEMONADE (ADD MINT)',
    titleAr: 'ليموناضة فريش (نعناع اضافي)',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.250,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 67,
    title: 'MOJITO FLAVORS',
    titleAr: 'موهيتو',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 2.500,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 68,
    title: 'CHAMPAIGN WHITE GRAPES BOTTLE 750ML (NON-ALCOHOLIC)',
    titleAr: 'بطل شامبيين عنب ابيض (غير كحولي) 750مل',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 6.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 69,
    title: 'SOFT DRINKS (Coke / Diet Coke / Sprite / Fanta)',
    titleAr: '(كوكاكولا / دايت كولا / سبرايت / فانتا) مشروبات غازية',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 1.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
   {
    id: 70,
    title: 'WATER',
    titleAr: 'ماء',
    categoryEn: 'colddrinks',
    category: 'Cold DRINKS / مشروبات باردة',
    price: 1.000,
    //img: '/images/maincourse/pizza2.jpg',
    // desc: `2 GRILLED CHICKEN, BROCCOLI, MUSHROOMS, CARROTS, GREEN 
    // BEANS`,
    // descAr: `قطعتين (2) دجاج مشوي، بروكولي، فطر، جزر، فاصوليا خضراء`,
   },   
];
export default menu;
